services:
  - type: web
    name: gdp-matcher-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /opt/render/project/src/data
      cp data/game_data_with_flags.json /opt/render/project/src/data/
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    healthCheckPath: /api/game?difficulty=medium
    autoDeploy: true 